// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH0aqHHP3hNDxRIgUYROhIbjsemY5UcRc',
    appId: '1:981964891221:web:a922e835e0d1d26b6fa0dc',
    messagingSenderId: '981964891221',
    projectId: 'mode-sweden',
    authDomain: 'mode-sweden.firebaseapp.com',
    storageBucket: 'mode-sweden.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2YVtruCk__KKG4TtqZiRcuTiWWHft4SQ',
    appId: '1:981964891221:android:737a793f49d3d0046fa0dc',
    messagingSenderId: '981964891221',
    projectId: 'mode-sweden',
    storageBucket: 'mode-sweden.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7nht6umgLAWHwSATnxCnZyj8onmoRh80',
    appId: '1:981964891221:ios:fc20105e8ddc71b76fa0dc',
    messagingSenderId: '981964891221',
    projectId: 'mode-sweden',
    storageBucket: 'mode-sweden.appspot.com',
    iosClientId: '981964891221-g1g7d2m0rnidodc132816umjbq224btj.apps.googleusercontent.com',
    iosBundleId: 'com.example.uberUi',
  );
}
